TRUNCATE TABLE geodata_config;

INSERT INTO geodata_config (estado, municipio, parroquia, sector) VALUES
('Aragua', 'José Rafael Revenga', 'El Consejo', 'La Casona'),
('Aragua', 'José Rafael Revenga', 'El Consejo', 'La Gruta'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Bella Vista'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Brisas de Aragua'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Brisas de Bucaral'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Cañaote'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Caobal'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Casco Central'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Ciudad Guayas'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Colinas de Bucaral'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Curiepe'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'El Beisbol'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'El Loro'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Jabillal'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Jerusalen'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'La Concepcion'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Las Lomitas'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Los Limites'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Los Panamericanos'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Santo Domingo'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Tabacal'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Tinapuey'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Trapiche del Medio'),
('Aragua', 'Santos Michelena', 'Las Tejerias', 'Variantes de Guaya'),
('Distrito Capital', 'Libertador', 'Coche', 'Coche'),
('Distrito Capital', 'Libertador', 'Coche', 'Fundapol'),
('Distrito Capital', 'Libertador', 'Coche', 'Las Mayas'),
('Distrito Capital', 'Libertador', 'El Valle', 'El Valle'),
('Distrito Capital', 'Libertador', 'La Vega', 'Las Torres'),
('Distrito Capital', 'Libertador', 'Sucre (catia)', 'Propatria'),
('Miranda', 'Carrizal', 'Carrizal', 'Barola'),
('Miranda', 'Carrizal', 'Carrizal', 'Barrio Bolivar'),
('Miranda', 'Carrizal', 'Carrizal', 'Brisas de Oriente'),
('Miranda', 'Carrizal', 'Carrizal', 'C.c Coliseo'),
('Miranda', 'Carrizal', 'Carrizal', 'C.c Don Pedro'),
('Miranda', 'Carrizal', 'Carrizal', 'C.c la Cascada'),
('Miranda', 'Carrizal', 'Carrizal', 'C.c Tibisay'),
('Miranda', 'Carrizal', 'Carrizal', 'Casco Central'),
('Miranda', 'Carrizal', 'Carrizal', 'Corralito'),
('Miranda', 'Carrizal', 'Carrizal', 'Jose Manuel Alvarez'),
('Miranda', 'Carrizal', 'Carrizal', 'Km 18'),
('Miranda', 'Carrizal', 'Carrizal', 'La Guadalupe'),
('Miranda', 'Carrizal', 'Carrizal', 'Llano Alto'),
('Miranda', 'Carrizal', 'Carrizal', 'Lomas de Urquia'),
('Miranda', 'Carrizal', 'Carrizal', 'Montaña Alta'),
('Miranda', 'Carrizal', 'Carrizal', 'Potrerito I'),
('Miranda', 'Carrizal', 'Carrizal', 'Potrero del Medio'),
('Miranda', 'Carrizal', 'Carrizal', 'Res. Alta Vista'),
('Miranda', 'Carrizal', 'Carrizal', 'Res. los Eucaliptos'),
('Miranda', 'Carrizal', 'Carrizal', 'Santa Eduviges'),
('Miranda', 'Carrizal', 'Carrizal', 'Yerba Buena'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Agua Fria'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Cachapal'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Cantarrana'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Casco Central'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Cocorote'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Cortada del Guayabo'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'El Aguacatal'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'El Calvario'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'El Guamal'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'El Ingenio'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'El Limon'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'El Naranjal'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'El Peñon'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'El Prado'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Guaicoco'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Guareguare'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'La Crucesita'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'La Culebrilla'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'La Oci'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Los Amistosos'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Los Colorados'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'San Jose'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'San Rafael'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta (san Diego Y San Jose de los Altos)', 'Vista Hermosa'),
('Miranda', 'Guaicaipuro', 'Los Teques', '23 de Enero'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Alberto Ravell'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Alto Verde'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Aquiles Nazoa'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Barrio la Cruz'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Barrio Miranda I'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Barrio Miranda Ii'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Brisas de Palo Alto'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Buenos Aires'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'C.c Ali Primera'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'C.c. Vasconia'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Carretera Vieja Caracas los Teques'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Centro los Teques'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Club Hipico'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Colinas del Angel'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Colinas del Paso'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Cooperativa Guaicaipuro'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Cumbre Rojas'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Ayacucho'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Barbecho'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Bosque'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Cabotaje'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Encanto'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Nacional'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Panadero'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Paso'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Pueblo'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Puinky'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Reten'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Rincon'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Tambor'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Trabuco'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Trigo'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Vigia'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Guaremal'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Hospital Victorino Santaella'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Jose Gregorio'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Estrella'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Fontanera'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Matica'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Quinta'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Lagunetica'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Las Cadenas'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Las Dalias'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Las Lomitas'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Alpes'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Amarillos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Barriales'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Cerritos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Lagos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Mangos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Panamericanos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Macarena Sur'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Mal Paso'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Manuela Saenz'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Palo Alto'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Punta Brava'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Quebrada la Virgen'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Ramo Verde'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Aldebaran'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Caracas'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Cima'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. el Chorrito'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Imola'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Knoop'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. la Cima'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Lagunetica'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Miracielos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Miraflores'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Parque las Americas'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Rio Arriba'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Santa Maria'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Tamari'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Tinantonia'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Tiuna'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Trigo Dorado'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. Yati'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Retamal'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Romulo Gallegos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Sant Omero'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Santa Eduviges'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Santa Eulalia'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Santa Rosa'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Solar de la Quinta'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Urb. Simon Bolivar'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Valle Alto'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Zona Industrial el Tambor'),
('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'Bosque de Pinos'),
('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'El Pueblo'),
('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'Pozo de Rosas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Agua Linda'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Arboleda'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.c Galeria las Americas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.c la Colina'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.c. Cepan'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.c. Club de Campo'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.c. Don Blas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.c. la Casona 2'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Club de Campo'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Amarillo'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Limon'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Paramo'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Pueblo'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Retiro'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Sitio'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Km 8'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'La Ermita'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'La Gonzalera'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'La Morita'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'La Oveja Negra'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'La Rosaleda'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Las Cumbres'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Las Minas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Las Polonias'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Los Castores'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Los Helechos'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Los Llaneros'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Res. el Rocio'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Res. las Churuatas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Res. Ops'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Res. San Antonio'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Rosaleda Norte'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Sierra Brava'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Zona Industrial las Minas');
