-- ============================================================
-- ACTUALIZACIÓN COMPLETA DE geodata_config
-- Ejecutar en el SQL Editor de Supabase
-- ============================================================

-- 1. Borrar todos los registros existentes
DELETE FROM geodata_config;

-- 2. Insertar todos los sectores actualizados y correctos
INSERT INTO geodata_config (parroquia, sector) VALUES 

-- Carrizal (24)
('Carrizal', 'Barola'),
('Carrizal', 'Brisas de Oriente'),
('Carrizal', 'C.C. Coliseo'),
('Carrizal', 'C.C. Don Pedro'),
('Carrizal', 'C.C. La Cascada'),
('Carrizal', 'C.C. Llano Alto'),
('Carrizal', 'Casco Central'),
('Carrizal', 'Colinas de Carrizal'),
('Carrizal', 'Corralito'),
('Carrizal', 'El Sitio'),
('Carrizal', 'José Manuel Álvarez'),
('Carrizal', 'La Carbonera'),
('Carrizal', 'La Ladera'),
('Carrizal', 'La Llovizna'),
('Carrizal', 'La Marcona'),
('Carrizal', 'Las Fresas'),
('Carrizal', 'Llano Alto'),
('Carrizal', 'Loma Gorda'),
('Carrizal', 'Lomas de Urquía'),
('Carrizal', 'Montaña Alta'),
('Carrizal', 'Potrerito'),
('Carrizal', 'Potrerito del Medio'),
('Carrizal', 'Santa Eduvigis'),
('Carrizal', 'Yerbabuena'),

-- Cecilio Acosta (24)
('Cecilio Acosta', 'Agua Fría'),
('Cecilio Acosta', 'C.C. Pasatiempo'),
('Cecilio Acosta', 'Carmen Sur'),
('Cecilio Acosta', 'Casco Central'),
('Cecilio Acosta', 'Cocorote'),
('Cecilio Acosta', 'Cortada del Guayabo'),
('Cecilio Acosta', 'El Colorado'),
('Cecilio Acosta', 'El Fogón'),
('Cecilio Acosta', 'El Limón'),
('Cecilio Acosta', 'El Peñón'),
('Cecilio Acosta', 'El Prado'),
('Cecilio Acosta', 'Guaicoco'),
('Cecilio Acosta', 'Guamas'),
('Cecilio Acosta', 'Guareguare'),
('Cecilio Acosta', 'Hacienda El Barranco'),
('Cecilio Acosta', 'La Oci'),
('Cecilio Acosta', 'Los Amistosos'),
('Cecilio Acosta', 'Nueva Generación'),
('Cecilio Acosta', 'Pasatiempo'),
('Cecilio Acosta', 'San José'),
('Cecilio Acosta', 'San Rafael de la Montaña'),
('Cecilio Acosta', 'Santa Eduvigis'),
('Cecilio Acosta', 'Urbanización Cerro Alto'),
('Cecilio Acosta', 'Urbanización Vista Hermosa'),

-- Coche (7)
('Coche', 'Coche (Casco Central)'),
('Coche', 'Cochecito'),
('Coche', 'La Rinconada'),
('Coche', 'Las Mayas'),
('Coche', 'Mercado Mayor de Coche'),
('Coche', 'Turmerito'),
('Coche', 'Veredas de Coche'),

-- El Consejo (4)
('El Consejo', 'Centro'),
('El Consejo', 'Sabaneta'),
('El Consejo', 'Santo Domingo'),
('El Consejo', 'Zona Industrial'),

-- El Paraíso
('El Paraíso', 'N/A'),

-- El Valle (7)
('El Valle', 'Casco Central'),
('El Valle', 'La Bandera'),
('El Valle', 'Las Casitas'),
('El Valle', 'Las Malvinas'),
('El Valle', 'Los Jardines de El Valle'),
('El Valle', 'Los Rosales'),
('El Valle', 'Prado de María'),

-- La Vega
('La Vega', 'N/A'),

-- Las Tejerías (22)
('Las Tejerías', 'Bella Vista'),
('Las Tejerías', 'Brisas de Bucaral'),
('Las Tejerías', 'Bucaral'),
('Las Tejerías', 'Casco Central'),
('Las Tejerías', 'Colinas de Bucaral'),
('Las Tejerías', 'Curiepén'),
('Las Tejerías', 'El Beisbol'),
('Las Tejerías', 'El Caballito'),
('Las Tejerías', 'El Jabillal'),
('Las Tejerías', 'El Loro'),
('Las Tejerías', 'Jerusalem'),
('Las Tejerías', 'La Cañada'),
('Las Tejerías', 'La Concepción'),
('Las Tejerías', 'La Estación'),
('Las Tejerías', 'La Gruta'),
('Las Tejerías', 'La Línea'),
('Las Tejerías', 'La Olla'),
('Las Tejerías', 'La Oveja'),
('Las Tejerías', 'Las Guayas'),
('Las Tejerías', 'Santa Maria'),
('Las Tejerías', 'Trapiche del Medio'),
('Las Tejerías', 'Variante de Guayas'),

-- Los Teques (96)
('Los Teques', '23 de Enero'),
('Los Teques', 'Alberto Ravell'),
('Los Teques', 'Alto Verde'),
('Los Teques', 'Alí Primera (incl. C.C.)'),
('Los Teques', 'Aquiles Nazoa'),
('Los Teques', 'Av. Bermúdez'),
('Los Teques', 'Av. Bertorelli Cisneros'),
('Los Teques', 'Av. Bicentenario'),
('Los Teques', 'Av. Bolívar'),
('Los Teques', 'Av. Francisco de Miranda'),
('Los Teques', 'Av. Víctor Batista'),
('Los Teques', 'Barrio Ayacucho'),
('Los Teques', 'Barrio La Cruz'),
('Los Teques', 'Barrio Miranda I y II'),
('Los Teques', 'Bosque Alto'),
('Los Teques', 'Brisas de Aragua'),
('Los Teques', 'Brisas de Palo Alto'),
('Los Teques', 'Buenos Aires'),
('Los Teques', 'C.C. El Hito'),
('Los Teques', 'C.C. Petrocas'),
('Los Teques', 'Carretera Vieja'),
('Los Teques', 'Cañaote'),
('Los Teques', 'Centro Los Teques'),
('Los Teques', 'Club Hípico'),
('Los Teques', 'Colina del Ángel'),
('Los Teques', 'Colinas del Paso'),
('Los Teques', 'Cumbre Azul'),
('Los Teques', 'Cumbre Roja'),
('Los Teques', 'El Barbecho'),
('Los Teques', 'El Bosque'),
('Los Teques', 'El Cabotaje'),
('Los Teques', 'El Chorrito'),
('Los Teques', 'El Encanto'),
('Los Teques', 'El Nacional'),
('Los Teques', 'El Panadero'),
('Los Teques', 'El Paso'),
('Los Teques', 'El Retén'),
('Los Teques', 'El Rincón'),
('Los Teques', 'El Sabil'),
('Los Teques', 'El Solar de la Quinta'),
('Los Teques', 'El Tambor'),
('Los Teques', 'El Tiuna'),
('Los Teques', 'El Trabuco'),
('Los Teques', 'El Trigo'),
('Los Teques', 'El Vigía'),
('Los Teques', 'Guaremal'),
('Los Teques', 'Hospital Victorino Santaella'),
('Los Teques', 'Imola'),
('Los Teques', 'José Gregorio Hernández'),
('Los Teques', 'Km 26'),
('Los Teques', 'Km 38'),
('Los Teques', 'La Cascarita (incl. Residencias)'),
('Los Teques', 'La Cima (incl. Residencias)'),
('Los Teques', 'La Estrella'),
('Los Teques', 'La Fontanera'),
('Los Teques', 'La Línea'),
('Los Teques', 'La Macarena'),
('Los Teques', 'La Mascota'),
('Los Teques', 'La Mata'),
('Los Teques', 'La Matica'),
('Los Teques', 'La Quinta'),
('Los Teques', 'Lagunetica (incl. Residencias)'),
('Los Teques', 'Las Cadenas'),
('Los Teques', 'Los Alpes'),
('Los Teques', 'Los Amarillos'),
('Los Teques', 'Los Andamios'),
('Los Teques', 'Los Apamates'),
('Los Teques', 'Los Barriales'),
('Los Teques', 'Los Cerritos'),
('Los Teques', 'Los Colorados'),
('Los Teques', 'Los Lagos'),
('Los Teques', 'Los Límites'),
('Los Teques', 'Los Nuevos Teques'),
('Los Teques', 'Los Panamericanos'),
('Los Teques', 'Mal Paso'),
('Los Teques', 'Miracielo'),
('Los Teques', 'Miraflores'),
('Los Teques', 'Moiral'),
('Los Teques', 'Montes Verdes'),
('Los Teques', 'Palo Alto'),
('Los Teques', 'Pan de Azúcar'),
('Los Teques', 'Parque Knoop'),
('Los Teques', 'Parque Las Américas'),
('Los Teques', 'Parque Los Coquitos (incl. Residencias)'),
('Los Teques', 'Puerta Morocha'),
('Los Teques', 'Punta Brava'),
('Los Teques', 'Quebrada La Virgen'),
('Los Teques', 'Ramo Verde'),
('Los Teques', 'Res. (Aldebaran, Yati)'),
('Los Teques', 'Retamal'),
('Los Teques', 'Romerito'),
('Los Teques', 'Río Arriba'),
('Los Teques', 'Rómulo Gallegos'),
('Los Teques', 'San Omero'),
('Los Teques', 'San Pedro'),
('Los Teques', 'Santa Eulalia'),
('Los Teques', 'Santa María'),
('Los Teques', 'Santa Rosa'),
('Los Teques', 'Simón Bolívar (Urb. y Res.)'),
('Los Teques', 'Tiuna'),
('Los Teques', 'Trigo Dorado (incl. Residencias)'),
('Los Teques', 'Tuqueque'),
('Los Teques', 'Urb. El Bosque'),
('Los Teques', 'Urb. San Camilo'),
('Los Teques', 'Urb. Tina Antonia'),
('Los Teques', 'Valle Alto'),
('Los Teques', 'Yati'),

-- San Antonio de los Altos (30)
('San Antonio de los Altos', 'Barrio Las Minas'),
('San Antonio de los Altos', 'Bosque Alegre'),
('San Antonio de los Altos', 'C.C. Casa Blanca'),
('San Antonio de los Altos', 'C.C. Club de Campo'),
('San Antonio de los Altos', 'C.C. Colinas'),
('San Antonio de los Altos', 'C.C. Don Blas'),
('San Antonio de los Altos', 'C.C. Galerías'),
('San Antonio de los Altos', 'C.C. La Casona (y La Casona II)'),
('San Antonio de los Altos', 'C.C. Los Castores'),
('San Antonio de los Altos', 'C.C. Los Llaneros'),
('San Antonio de los Altos', 'Casco Histórico'),
('San Antonio de los Altos', 'Churuatas'),
('San Antonio de los Altos', 'El Cují'),
('San Antonio de los Altos', 'El Picacho'),
('San Antonio de los Altos', 'El Páramo (incl. Residencias)'),
('San Antonio de los Altos', 'El Retiro'),
('San Antonio de los Altos', 'La Ermita'),
('San Antonio de los Altos', 'La Morita'),
('San Antonio de los Altos', 'La Pomarrosa'),
('San Antonio de los Altos', 'La Rosaleda'),
('San Antonio de los Altos', 'Las Minas (incl. Zona Industrial)'),
('San Antonio de los Altos', 'Las Polonias Nuevas y Viejas'),
('San Antonio de los Altos', 'Los Castores'),
('San Antonio de los Altos', 'Los Helechos'),
('San Antonio de los Altos', 'Los Samanes'),
('San Antonio de los Altos', 'OPS'),
('San Antonio de los Altos', 'Pueblo de San Antonio'),
('San Antonio de los Altos', 'Res. (Anita, San Antonio)'),
('San Antonio de los Altos', 'Sierra Brava'),
('San Antonio de los Altos', 'Terrazas de La Rosaleda'),

-- San Pedro de los Altos (4)
('San Pedro de los Altos', 'Bosque de Pinos'),
('San Pedro de los Altos', 'El Garabato'),
('San Pedro de los Altos', 'Pozo de Rosas'),
('San Pedro de los Altos', 'Pueblo'),

-- Sucre (12)
('Sucre', 'Alta Vista'),
('Sucre', 'Blandín'),
('Sucre', 'Casalta'),
('Sucre', 'El Cuartel'),
('Sucre', 'Gramoven'),
('Sucre', 'La Silsa'),
('Sucre', 'Lomas de Urdaneta'),
('Sucre', 'Los Flores de Catia'),
('Sucre', 'Los Frailes'),
('Sucre', 'Los Magallanes de Catia'),
('Sucre', 'Propatria'),
('Sucre', 'Ruperto Lugo');
