DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='geodata_config' AND column_name='estado') THEN
        ALTER TABLE geodata_config ADD COLUMN estado TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='geodata_config' AND column_name='municipio') THEN
        ALTER TABLE geodata_config ADD COLUMN municipio TEXT;
    END IF;
END $$;

-- 2. Crear tabla actividades en Supabase
CREATE TABLE IF NOT EXISTS actividades (
    id SERIAL PRIMARY KEY,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    asesor TEXT NOT NULL,
    tipo TEXT NOT NULL,
    solicitudes INTEGER DEFAULT 0,
    clientes_captados INTEGER DEFAULT 0,
    volantes INTEGER DEFAULT 0,
    llamadas_info INTEGER DEFAULT 0,
    llamadas_agenda INTEGER DEFAULT 0,
    estado TEXT,
    municipio TEXT,
    parroquia TEXT,
    sector TEXT,
    condominio TEXT,
    notas TEXT,
    reporte_wa TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Limpiar datos viejos de geodata_config
TRUNCATE TABLE geodata_config;

-- 4. Insertar Jerarquía Completa
INSERT INTO geodata_config (estado, municipio, parroquia, sector) VALUES 
('Aragua', 'José Rafael Revenga', 'El Consejo', 'Centro'),
('Aragua', 'José Rafael Revenga', 'El Consejo', 'Sabaneta'),
('Aragua', 'José Rafael Revenga', 'El Consejo', 'Santo Domingo'),
('Aragua', 'José Rafael Revenga', 'El Consejo', 'Zona Industrial'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Bella Vista'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Brisas de Bucaral'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Bucaral'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Casco Central'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Colinas de Bucaral'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Curiepé'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'El Beisbol'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'El Caballito'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'El Jabillal'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'El Loro'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Jerusalem'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'La Cañada'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'La Concepción'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'La Estación'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'La Gruta'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'La Línea'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'La Olla'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'La Oveja'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Las Guayas'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Santa Maria'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Trapiche del Medio'),
('Aragua', 'Santos Michelena', 'Las Tejerías', 'Variante de Guayas'),
('Distrito Capital', 'Libertador', 'Coche', 'Coche (Casco Central)'),
('Distrito Capital', 'Libertador', 'Coche', 'Cochecito'),
('Distrito Capital', 'Libertador', 'Coche', 'La Rinconada'),
('Distrito Capital', 'Libertador', 'Coche', 'Las Mayas'),
('Distrito Capital', 'Libertador', 'Coche', 'Mercado Mayor de Coche'),
('Distrito Capital', 'Libertador', 'Coche', 'Turmerito'),
('Distrito Capital', 'Libertador', 'Coche', 'Veredas de Coche'),
('Distrito Capital', 'Libertador', 'El Paraíso', 'N/A'),
('Distrito Capital', 'Libertador', 'El Valle', 'Casco Central'),
('Distrito Capital', 'Libertador', 'El Valle', 'La Bandera'),
('Distrito Capital', 'Libertador', 'El Valle', 'Las Casitas'),
('Distrito Capital', 'Libertador', 'El Valle', 'Las Malvinas'),
('Distrito Capital', 'Libertador', 'El Valle', 'Los Jardines de El Valle'),
('Distrito Capital', 'Libertador', 'El Valle', 'Los Rosales'),
('Distrito Capital', 'Libertador', 'El Valle', 'Prado de María'),
('Distrito Capital', 'Libertador', 'La Vega', 'N/A'),
('Distrito Capital', 'Libertador', 'Sucre', 'Alta Vista'),
('Distrito Capital', 'Libertador', 'Sucre', 'Blandín'),
('Distrito Capital', 'Libertador', 'Sucre', 'Casalta'),
('Distrito Capital', 'Libertador', 'Sucre', 'El Cuartel'),
('Distrito Capital', 'Libertador', 'Sucre', 'Gramoven'),
('Distrito Capital', 'Libertador', 'Sucre', 'La Silsa'),
('Distrito Capital', 'Libertador', 'Sucre', 'Lomas de Urdaneta'),
('Distrito Capital', 'Libertador', 'Sucre', 'Los Flores de Catia'),
('Distrito Capital', 'Libertador', 'Sucre', 'Los Frailes'),
('Distrito Capital', 'Libertador', 'Sucre', 'Los Magallanes de Catia'),
('Distrito Capital', 'Libertador', 'Sucre', 'Propatria'),
('Distrito Capital', 'Libertador', 'Sucre', 'Ruperto Lugo'),
('Miranda', 'Carrizal', 'Carrizal', 'Barola'),
('Miranda', 'Carrizal', 'Carrizal', 'Brisas de Oriente'),
('Miranda', 'Carrizal', 'Carrizal', 'C.C. Coliseo'),
('Miranda', 'Carrizal', 'Carrizal', 'C.C. Don Pedro'),
('Miranda', 'Carrizal', 'Carrizal', 'C.C. La Cascada'),
('Miranda', 'Carrizal', 'Carrizal', 'C.C. Llano Alto'),
('Miranda', 'Carrizal', 'Carrizal', 'Casco Central'),
('Miranda', 'Carrizal', 'Carrizal', 'Colinas de Carrizal'),
('Miranda', 'Carrizal', 'Carrizal', 'Corralito'),
('Miranda', 'Carrizal', 'Carrizal', 'El Sitio'),
('Miranda', 'Carrizal', 'Carrizal', 'José Manuel Álvarez'),
('Miranda', 'Carrizal', 'Carrizal', 'La Carbonera'),
('Miranda', 'Carrizal', 'Carrizal', 'La Ladera'),
('Miranda', 'Carrizal', 'Carrizal', 'La Llovizna'),
('Miranda', 'Carrizal', 'Carrizal', 'La Marcona'),
('Miranda', 'Carrizal', 'Carrizal', 'Las Fresas'),
('Miranda', 'Carrizal', 'Carrizal', 'Llano Alto'),
('Miranda', 'Carrizal', 'Carrizal', 'Loma Gorda'),
('Miranda', 'Carrizal', 'Carrizal', 'Lomas de Urquía'),
('Miranda', 'Carrizal', 'Carrizal', 'Montaña Alta'),
('Miranda', 'Carrizal', 'Carrizal', 'Potrerito'),
('Miranda', 'Carrizal', 'Carrizal', 'Potrerito del Medio'),
('Miranda', 'Carrizal', 'Carrizal', 'Santa Eduvigis'),
('Miranda', 'Carrizal', 'Carrizal', 'Yerbabuena'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Agua Fría'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'C.C. Pasatiempo'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Carmen Sur'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Casco Central'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Cocorote'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Cortada del Guayabo'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'El Colorado'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'El Fogón'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'El Limón'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'El Peñón'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'El Prado'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Guaicoco'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Guamas'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Guareguare'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Hacienda El Barranco'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'La Oci'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Los Amistosos'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Nueva Generación'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Pasatiempo'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'San José'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'San Rafael de la Montaña'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Santa Eduvigis'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Urbanización Cerro Alto'),
('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'Urbanización Vista Hermosa'),
('Miranda', 'Guaicaipuro', 'Los Teques', '23 de Enero'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Alberto Ravell'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Alto Verde'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Alí Primera (incl. C.C.)'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Aquiles Nazoa'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Av. Bermúdez'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Av. Bertorelli Cisneros'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Av. Bicentenario'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Av. Bolívar'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Av. Francisco de Miranda'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Av. Víctor Batista'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Barrio Ayacucho'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Barrio La Cruz'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Barrio Miranda I y II'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Bosque Alto'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Brisas de Aragua'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Brisas de Palo Alto'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Buenos Aires'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'C.C. El Hito'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'C.C. Petrocas'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Carretera Vieja'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Cañaote'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Centro Los Teques'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Club Hípico'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Colina del Ángel'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Colinas del Paso'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Cumbre Azul'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Cumbre Roja'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Barbecho'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Bosque'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Cabotaje'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Chorrito'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Encanto'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Nacional'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Panadero'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Paso'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Retén'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Rincón'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Sabil'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Solar de la Quinta'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Tambor'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Tiuna'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Trabuco'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Trigo'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'El Vigía'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Guaremal'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Hospital Victorino Santaella'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Imola'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'José Gregorio Hernández'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Km 26'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Km 38'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Cascarita (incl. Residencias)'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Cima (incl. Residencias)'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Estrella'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Fontanera'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Línea'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Macarena'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Mascota'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Mata'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Matica'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'La Quinta'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Lagunetica (incl. Residencias)'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Las Cadenas'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Alpes'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Amarillos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Andamios'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Apamates'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Barriales'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Cerritos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Colorados'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Lagos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Límites'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Nuevos Teques'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Los Panamericanos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Mal Paso'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Miracielo'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Miraflores'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Moiral'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Montes Verdes'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Palo Alto'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Pan de Azúcar'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Parque Knoop'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Parque Las Américas'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Parque Los Coquitos (incl. Residencias)'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Puerta Morocha'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Punta Brava'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Quebrada La Virgen'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Ramo Verde'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Res. (Aldebaran'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Retamal'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Romerito'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Río Arriba'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Rómulo Gallegos'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'San Omero'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'San Pedro'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Santa Eulalia'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Santa María'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Santa Rosa'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Simón Bolívar (Urb. y Res.)'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Tiuna'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Trigo Dorado (incl. Residencias)'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Tuqueque'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Urb. El Bosque'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Urb. San Camilo'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Urb. Tina Antonia'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Valle Alto'),
('Miranda', 'Guaicaipuro', 'Los Teques', 'Yati)'),
('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'Bosque de Pinos'),
('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'El Garabato'),
('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'Pozo de Rosas'),
('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'Pueblo'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Barrio Las Minas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Bosque Alegre'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.C. Casa Blanca'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.C. Club de Campo'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.C. Colinas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.C. Don Blas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.C. Galerías'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.C. La Casona (y La Casona II)'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.C. Los Castores'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'C.C. Los Llaneros'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Casco Histórico'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Churuatas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Cují'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Picacho'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Páramo (incl. Residencias)'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'El Retiro'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'La Ermita'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'La Morita'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'La Pomarrosa'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'La Rosaleda'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Las Minas (incl. Zona Industrial)'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Las Polonias Nuevas y Viejas'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Los Castores'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Los Helechos'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Los Samanes'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'OPS'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Pueblo de San Antonio'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Res. (Anita'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'San Antonio)'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Sierra Brava'),
('Miranda', 'Los Salias', 'San Antonio de los Altos', 'Terrazas de La Rosaleda');

-- ============================================================
-- FIN DE CONFIGURACIÓN
-- ============================================================
